// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChirp = `-- name: CreateChirp :one

insert into chirpy(
    id, 
    created_at, 
    updated_at, 
    body, 
    user_id
) values(
    gen_random_uuid(),
    now(),
    now(),
    $1, 
    $2
)

returning id, created_at, updated_at, body, user_id
`

type CreateChirpParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirpy, error) {
	row := q.db.QueryRowContext(ctx, createChirp, arg.Body, arg.UserID)
	var i Chirpy
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deleteChirp = `-- name: DeleteChirp :exec
delete from chirpy
`

func (q *Queries) DeleteChirp(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteChirp)
	return err
}

const getChirp = `-- name: GetChirp :one
select id, created_at, updated_at, body, user_id from chirpy WHERE id = $1
`

func (q *Queries) GetChirp(ctx context.Context, id uuid.UUID) (Chirpy, error) {
	row := q.db.QueryRowContext(ctx, getChirp, id)
	var i Chirpy
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const getChirps = `-- name: GetChirps :many
select id, created_at, updated_at, body, user_id FROM chirpy
ORDER BY created_at ASC
`

func (q *Queries) GetChirps(ctx context.Context) ([]Chirpy, error) {
	rows, err := q.db.QueryContext(ctx, getChirps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirpy
	for rows.Next() {
		var i Chirpy
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
